# create_md_pages configuration file for app-compatibility-list.md
---
#required - shows up in the title of the page on html and in the <title> tags
title: "Apps With Known Compatibility Issues"

#required - description shows up in meta info for the page and if the page is linked
#to in related/featured articles lists
description: "Apps With Known Compatibility Issues with GrapheneOS"

# set an alias to this page because the whole url is so long and not fun to share
# zola supports multiple aliases, but just using one here because no point in setting many
alias: "bad-apps"

#optional
before_text: |
  When doing research about GrapheneOS, some people may find inaccurate information suggesting that
  many apps don't work on GrapheneOS. This just isn't true. The truth is the vast majority of apps work
  great with GrapheneOS.
  
  The emojis below mean the following:
  
  - ✅ - The app works in general or works without listed restrictions
  - ⚠️ - The app works, but only if the app is configured to run using Exploit Protection Compatibility Mode
  - ❌ - The app doesn't work at all on GrapheneOS, or it has a listed restriction
  - ❓ - It's unknown whether the app works as listed

  If any information on this list is incorrect, please open an issue on this site's
  {{ github_issues_link( text = "GitHub Issue Tracker") }}, or submit a pull request for the affected app.

  ---

#optional
after_text: null