# create_md_pages configuration file for app-compatibility-list.md
---
#required - shows up in the title of the page on html and in the <title> tags
title: "App Compatibility List"

#required - description shows up in meta info for the page and if the page is linked
#to in related/featured articles lists
description: "App Compatibility List for GrapheneOS"

# set an alias to this page because the whole url is so long and not fun to share
# zola supports multiple aliases, but just using one here because no point in setting many
alias: "apps"

#optional
before_text: |
  This list is an attempt to help the community track app compatibility and whether apps work normally or need
  [Exploit Protection Compatibility Mode](@/app-compatibility/exploit_protection_compatibility_mode.md)
  enabled, as well as whether apps rely on Sandboxed Google Play to run, or the occasional app that refuses
  to launch unless it's installed by Google Play.

  This page is a work in progress. The data are accurate, but the page layout may change.
  
  The emojis below mean the following:
  
  - ✅ - The app works in general or works without listed restrictions
  - ⚠️ - The app works, but only if the app is configured to run using Exploit Protection Compatibility Mode
  - ❌ - The app doesn't work at all on GrapheneOS, or it has a listed restriction
  - ❓ - It's unknown whether the app works as listed

  If any information on this list is incorrect, please open an issue on this site's
  {{ github_issues_link( text = "GitHub Issue Tracker") }}, or submit a pull request for the affected app.

  ---

#optional
after_text: null