name: "Submit your app compatilibity report"
description: Contribute by submitting your report to the [App compatibility with GrapheneOS list](https://other8026.github.io/community-docs/app-compatibility/app-compat-list/) - enabling other GrapheneOS users to easily determine whether it's supported.
labels: ["app compat report"]
title: "App Report: [Replace with 'New' or 'Update' <App name>]"
body:
  - type: markdown
    attributes:
      value: |
        Help out the GrapheneOS community by sharing whether an app works or not.
  - type: input
    id: app-name
    attributes:
      label: App name
      description: |
        Please enter the app's name as it appears on your phone.
      placeholder: Signal
    validations:
      required: true
  - type: input
    id: package-name
    attributes:
      label: App package name (Application ID)
      description: |
        Please enter the app's package name here (i.e. com.company.app)

        `Settings` → `Apps` → `All apps` → `<app_name>` → `Store` → `App ID / Package name`
      placeholder: org.thoughtcrime.securesms
    validations:
      required: true
  - type: dropdown
    id: works
    attributes:
      label: The app works
      description: It works on GrapheneOS, even if it requires Sandboxed Google Play, etc.
      multiple: false
      options:
        - No
        - Yes
    validations:
        required: true
  - type: dropdown
    id: without-compat-mode
    attributes:
      label: The app works without Exploit Protection Compatibility Mode
      description: `Settings` → `Apps` → `All apps` → `<app_name>` → `Advanced` → `Exploit protection compatibility mode`
      multiple: false
      options:
        - No
        - Yes
    validations:
        required: true
  - type: dropdown
    id: without-gms
    attributes:
      label: Works without Google Play
      description: Does the app work without Sandboxed Google Play installed in the same profile?
      multiple: false
      options:
        - Unsure
        - No
        - Yes
    validations:
        required: true
  - type: dropdown
    id: without-installed-by-play
    attributes:
      label: Works even if not installed by Google Play
      multiple: false
      options:
        - Unsure
        - No
        - Yes
    validations:
        required: true
  - type: textarea
    id: comments
    attributes:
      label: Any additional comments
      description: |
        If there are any other comments about this app's compatibility with GrapheneOS, please write it here.
