name: Check Zola site on push to dev

on:
  push:
    branches: ["dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@v2
        with:
          tool: zola
      - name: install create_md_pages
        run: cargo install --git https://github.com/other8026/create_md_pages.git
      - name: run create_md_pages --run
        run: create_md_pages --run --app-files-folder ./app-compat-files/ --output-md-file ./content/app-compatibility/app-compat-list.md --yaml-file ./app-compat-config.yaml
      - name: Check site
        run: zola check
